networks:
  server_bridge:
    external: true
  lab_bridge: {}
    

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PB_VERSION: ${PB_VERSION:-0.35.0}
    
    restart: always
    # ports:
    #   - "8090:8090" # Exposed via Traefik, no need to expose here
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_public:/pb/pb_public
    command: ["pocketbase", "serve", "--http=0.0.0.0:8090"]

    networks:
      - server_bridge
      - lab_bridge
    labels:
      traefik.enable: true
      traefik.docker.network: server_bridge
      traefik.http.services.lab.loadbalancer.server.port: 8090
      traefik.http.routers.lab.rule: Host(`lab.travis.wang`)
      traefik.http.routers.lab.entrypoints: https
      traefik.http.routers.lab.tls: true
      traefik.http.routers.lab.tls.certresolver: dnspod
      traefik.http.routers.lab.tls.domains[0].main: travis.wang
      traefik.http.routers.lab.tls.domains[0].sans: "*.travis.wang"
